siteTitle = "Tyler McGinnis: React, JavaScript, and Front End related tutorials and resources"

siteDescr = "Partner at React Training. Google Developer Expert."

siteAuthor = "Tyler McGinnis"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/tylermcginnis33"
siteGithubUrl = "https://github.com/tylermcginnis"
siteFacebookUrl="https://www.facebook.com/tylermcginnis.dev"
siteYoutubeUrl="https://www.youtube.com/tylermcginnis"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = "UA-35670702-1"

linkPrefix = "/"

siteDescription = "Partner at React Training. Google Developer Expert. React, JavaScript, and Front End related tutorials and resources."

locale = "en_US"

shareTitle = "Tyler McGinnis' Blog"

avatar = "https://tylermcginnis.com/tyler-mcginnis.jpg"

canonicalURL = "https://tylermcginnis.com"